INSERT INTO settings (id, category, value, sort_order, active) VALUES
(19, 'birosag', 'Érdi Járásbíróság', 0, true),
(20, 'birosag', 'Budapest Környéki Törvényszék', 0, true),
(21, 'birosag', 'Nagykátai Járásbíróság', 0, true),
(22, 'birosag', 'Váci Járásbíróság', 0, true),
(23, 'birosag', 'Gödöllői Járásbíróság', 0, true),
(24, 'birosag', 'Szigetszentmiklósi Járásbíróság', 0, true),
(25, 'birosag', 'Ráckevei Járásbíróság', 0, true),
(31, 'resztvevok', 'Alperes - Felperes', 0, true),
(32, 'resztvevok', 'Terhelt - Vádló', 0, true),
(38, 'room', 'BKT_A_01T', 0, true),
(39, 'room', 'BKT_A_02T', 0, true),
(40, 'room', 'BKT_A_03T', 0, true),
(43, 'room', 'BKT_A_04T', 0, true),
(44, 'room', 'BKT_A_10T', 0, true),
(45, 'room', 'BKT_A_11T', 0, true),
(46, 'room', 'BKT_A_12T', 0, true),
(47, 'room', 'BKT_A_15T', 0, true),
(48, 'room', 'BKT_A_16T', 0, true),
(49, 'room', 'BKT_A_17T', 0, true),
(50, 'room', 'BKT_A_18T', 0, true),
(51, 'room', 'BKT_A_19T', 0, true),
(52, 'room', 'BKT.B.01T', 0, true),
(53, 'room', 'BKT_A_28T', 0, true),
(54, 'room', 'BKT_A_29T', 0, true),
(55, 'room', 'BKT_A_51T', 0, true),
(56, 'room', 'BKT_A_52T', 0, true),
(57, 'room', 'BKT_A_54T', 0, true),
(58, 'room', 'BKT_A_20T', 0, true),
(59, 'room', 'BKT_A_21T', 0, true),
(60, 'room', 'BKT_A_22T', 0, true),
(61, 'room', 'BKT_A_23T', 0, true),
(62, 'room', 'BKT_A_24T', 0, true),
(63, 'room', 'BKT_A_25T', 0, true),
(64, 'room', 'BKT_A_35T', 0, true),
(65, 'room', 'BKT_A_26T', 0, true),
(66, 'room', 'BKT_A_27T', 0, true),
(67, 'room', 'BKT_A_30T', 0, true),
(68, 'room', 'BKT_A_32T', 0, true),
(69, 'room', 'BKT_A_34T', 0, true),
(70, 'room', 'BKT_A_39T', 0, true),
(71, 'room', 'BKT_A_40T', 0, true),
(72, 'room', 'BKT_A_42T', 0, true),
(73, 'room', 'BKT_A_43T', 0, true),
(74, 'room', 'BKT_A_46T', 0, true),
(75, 'room', 'BKT_A_47T', 0, true),
(76, 'room', 'BKT_A_48T', 0, true),
(77, 'room', 'BKT_A_50T', 0, true),
(78, 'room', 'BKT_B_4.24', 0, true),
(79, 'room', 'BKT_A_05T', 0, true),
(80, 'room', 'BKT_A_06T', 0, true),
(81, 'room', 'BKT_A_07T', 0, true),
(82, 'room', 'BKT_A_08T', 0, true),
(83, 'room', 'BKT_A_09T', 0, true),
(84, 'room', 'BKT_A_33T', 0, true),
(187, 'tanacs', 'dr. Batta Júlia Dóra', 0, true),
(188, 'tanacs', 'Dénesiné dr. Tóth Ildikó', 0, true),
(189, 'tanacs', 'dr. Batta Júlia Dóra', 0, true),
(190, 'tanacs', 'dr. Borbély Attila', 0, true),
(191, 'tanacs', 'dr. Czéh Ágnes', 0, true),
(192, 'tanacs', 'dr. Fazekas Ágnes', 0, true),
(193, 'tanacs', 'dr. Fejős Gabriella', 0, true),
(194, 'tanacs', 'dr. Hazafi Hildegárd', 0, true),
(195, 'tanacs', 'dr. Holdampf Gusztáv', 0, true),
(196, 'tanacs', 'dr. Kasnyik Adrienn Flóra', 0, true),
(197, 'tanacs', 'dr. Katona Rita', 0, true),
(198, 'tanacs', 'dr. Kemény Kornélia', 0, true),
(199, 'tanacs', 'dr. Kenese Attila', 0, true),
(200, 'tanacs', 'dr. Keyha Ádám', 0, true),
(201, 'tanacs', 'dr. Kiss Andrea', 0, true),
(202, 'tanacs', 'dr. Kövesdi Gergely Mihály', 0, true),
(203, 'tanacs', 'dr. Laki Zita', 0, true),
(204, 'tanacs', 'dr. Léhmann Zoltán', 0, true),
(205, 'tanacs', 'dr. Márta Mária', 0, true),
(206, 'tanacs', 'dr. Máthé Magdolna', 0, true),
(207, 'tanacs', 'dr. Oláh Gaszton', 0, true),
(208, 'tanacs', 'dr. Opóczky László', 0, true),
(209, 'tanacs', 'dr. Palásti Sándor', 0, true),
(210, 'tanacs', 'dr. Puskás Ágnes', 0, true),
(211, 'tanacs', 'dr. Répássy Andrea', 0, true),
(212, 'tanacs', 'dr. Somody Nóra', 0, true),
(213, 'tanacs', 'dr. Szabó Anikó', 0, true),
(214, 'tanacs', 'dr. Szalay Csaba', 0, true),
(215, 'tanacs', 'dr. Szegedi Gyöngyvér', 0, true),
(216, 'tanacs', 'dr. Szente László', 0, true),
(217, 'tanacs', 'dr. Tarjányi Márta', 0, true),
(218, 'tanacs', 'dr. Tóth Zsófia Judit', 0, true),
(219, 'tanacs', 'dr. Turu Olga', 0, true),
(220, 'tanacs', 'dr. Urbán-Kiss Andrea', 0, true),
(221, 'tanacs', 'dr. Zsálek Henriett', 0, true),
(222, 'tanacs', 'dr. Zsembery Antal', 0, true),
(223, 'tanacs', 'Ila-Tóthné dr. Vörös Erika', 0, true),
(224, 'tanacs', 'Nyáregyháziné dr. Sánta Emese', 0, true),
(225, 'tanacs', 'Zrupkóné dr. Szender Zsuzsa', 0, true),
(226, 'tanacs', 'dr. Bicskey Eszter', 0, true),
(227, 'tanacs', 'dr. Dénesi András Marcell', 0, true),
(228, 'tanacs', 'dr. Erdős András', 0, true),
(229, 'tanacs', 'dr. Garáné dr. Horváth Diána', 0, true),
(230, 'tanacs', 'dr. Helmeczy Zsófia', 0, true),
(231, 'tanacs', 'dr. Jobbágy János', 0, true),
(232, 'tanacs', 'dr. Keszthelyi Alajos', 0, true),
(233, 'tanacs', 'dr. Bak Szilvia', 0, true),
(234, 'tanacs', 'dr. Bognár Ildikó', 0, true),
(235, 'tanacs', 'dr. Butyka Mária', 0, true),
(236, 'tanacs', 'dr. Durucz-Baráth Zsuzsanna', 0, true),
(237, 'tanacs', 'dr. Kispál Sándorné dr. Balogh Ágnes', 0, true),
(238, 'tanacs', 'dr. Kun Mariann', 0, true),
(239, 'tanacs', 'dr. Liptai Andrea', 0, true),
(240, 'tanacs', 'dr. Németh Erika', 0, true),
(241, 'tanacs', 'dr. Pásztorné Bilik Sarolta', 0, true),
(242, 'tanacs', 'dr. Péli Szilvia', 0, true),
(243, 'tanacs', 'dr. Gerber Tamás', 0, true),
(244, 'tanacs', 'dr. Liziczay Sándor', 0, true),
(245, 'tanacs', 'dr. Szabó Edit', 0, true),
(246, 'tanacs', 'dr. Antal Ildikó', 0, true),
(247, 'tanacs', 'dr. Balka Viktória', 0, true),
(248, 'tanacs', 'dr. Fördös István Tamás', 0, true),
(249, 'tanacs', 'dr. György Mária', 0, true),
(250, 'tanacs', 'dr. Herczeg Margit Márta', 0, true),
(251, 'tanacs', 'dr. Károlyi Kristóf', 0, true),
(252, 'tanacs', 'dr. Konkoly Marianna', 0, true),
(253, 'tanacs', 'dr. Lóránt István', 0, true),
(254, 'tanacs', 'dr. Neumann Zita', 0, true),
(255, 'tanacs', 'dr. Paisné dr. Kolozsvári Ágnes', 0, true),
(256, 'tanacs', 'dr. Pásztor Csaba', 0, true),
(257, 'tanacs', 'dr. Pintér Mária', 0, true),
(258, 'tanacs', 'dr. Ruff Edit', 0, true),
(259, 'tanacs', 'dr. Rusznák Anita', 0, true),
(260, 'tanacs', 'dr. Skrabski Luca', 0, true),
(261, 'tanacs', 'dr. Smuk Anna', 0, true),
(262, 'tanacs', 'dr. Szabó Annamária', 0, true),
(263, 'tanacs', 'dr. Tiszavölgyi Gyöngyvér', 0, true),
(264, 'tanacs', 'dr. Vida-Szabó Katalin', 0, true),
(265, 'tanacs', 'dr. Windecker Erika', 0, true),
(266, 'tanacs', 'Hargitainé dr. Iharos Ágnes', 0, true),
(267, 'tanacs', 'Spiegelbergerné dr. Pofonka Mariann', 0, true),
(268, 'tanacs', 'Bodnárné dr. Kolozsy Andrea dr.', 0, true),
(269, 'tanacs', 'dr. Bacsa Andrea', 0, true),
(270, 'tanacs', 'dr. Bartal Mónika', 0, true),
(271, 'tanacs', 'dr. Bene Enikő Inge', 0, true),
(272, 'tanacs', 'dr. Bozsó Péter', 0, true),
(273, 'tanacs', 'dr. Csőre Eszter', 0, true),
(274, 'tanacs', 'dr. Dávid Irén', 0, true),
(275, 'tanacs', 'dr. Dvoracsek Kutasi Dorottya', 0, true),
(276, 'tanacs', 'dr. Fekete Molnár Orsolya', 0, true),
(277, 'tanacs', 'dr. Horányi Cintia', 0, true),
(278, 'tanacs', 'dr. Kiss Georgina', 0, true),
(279, 'tanacs', 'dr. Kovács Balázs', 0, true),
(280, 'tanacs', 'dr. Króneisz Gábor', 0, true),
(281, 'tanacs', 'dr. Laky Edit Anita', 0, true),
(282, 'tanacs', 'dr. Lejer Barbara', 0, true),
(283, 'tanacs', 'dr. Minya Krisztián', 0, true),
(284, 'tanacs', 'dr. Nagy Gábor', 0, true),
(285, 'tanacs', 'dr. Rozgonyi-Wurst Katalin', 0, true),
(286, 'tanacs', 'dr. Sághi Rita', 0, true),
(287, 'tanacs', 'dr. Sándor Valter Pál', 0, true),
(288, 'tanacs', 'dr. Szincsák-Szászi Judit', 0, true),
(289, 'tanacs', 'dr. Szivák József', 0, true),
(290, 'tanacs', 'dr. Szomszéd Éva', 0, true),
(291, 'tanacs', 'dr. Tergalecz Eszter', 0, true),
(292, 'tanacs', 'dr. Tóth Éva Rita', 0, true),
(293, 'tanacs', 'Jakabné dr. Sándor Nóra', 0, true),
(294, 'tanacs', 'Tihanyiné dr. Matejcsik Emma Ágnes', 0, true),
(295, 'tanacs', 'dr. Ajtay-Horváth Viola', 0, true),
(296, 'tanacs', 'dr. Dudás Lilian', 0, true),
(297, 'tanacs', 'dr. Keszthelyi Bernadett', 0, true),
(298, 'tanacs', 'dr. Krátky Ákos', 0, true),
(299, 'tanacs', 'dr. Litke Ágota', 0, true),
(300, 'tanacs', 'dr. Maschl Ildikó', 0, true),
(301, 'tanacs', 'dr. Németh Zoltán', 0, true),
(302, 'tanacs', 'dr. Pokorny Gabriella', 0, true),
(303, 'tanacs', 'dr. Simon Judit', 0, true),
(304, 'tanacs', 'Beszterceyné dr. Benedek Tímea', 0, true),
(305, 'tanacs', 'Csedrekiné dr. Tóth Boglárka', 0, true),
(306, 'tanacs', 'dr. Ágoston Zoltán', 0, true),
(307, 'tanacs', 'dr. Aszódi László', 0, true),
(308, 'tanacs', 'dr. Bogdán Viola', 0, true),
(309, 'tanacs', 'dr. Csécsei Etele', 0, true),
(310, 'tanacs', 'dr. Csorba Anna', 0, true),
(311, 'tanacs', 'dr. Dancza Judit Katalin', 0, true),
(312, 'tanacs', 'dr. Domonkos Gyöngyi', 0, true),
(313, 'tanacs', 'dr. Élő-Prosszer Bernadett', 0, true),
(314, 'tanacs', 'dr. Erdeiné dr. Veres Ágnes', 0, true),
(315, 'tanacs', 'dr. Fehérné dr. Gaál Tünde', 0, true),
(316, 'tanacs', 'dr. Fekete Henrietta', 0, true),
(317, 'tanacs', 'dr. Félegyházy-Megyesi Fatime', 0, true),
(318, 'tanacs', 'dr. Gaál Erika', 0, true),
(319, 'tanacs', 'dr. Gajdos István', 0, true),
(320, 'tanacs', 'dr. Grasalkovits Irén', 0, true),
(321, 'tanacs', 'dr. Győrffy Katalin', 0, true),
(322, 'tanacs', 'dr. Hajdu Csaba', 0, true),
(323, 'tanacs', 'dr. Horváth Ildikó', 0, true),
(324, 'tanacs', 'dr. Jakab Ildikó Mónika', 0, true),
(325, 'tanacs', 'dr. Káldy Péter', 0, true),
(326, 'tanacs', 'dr. Kardos Gyula', 0, true),
(327, 'tanacs', 'dr. Kiss Éva', 0, true),
(328, 'tanacs', 'dr. Kiss Márta', 0, true),
(329, 'tanacs', 'dr. Klement Katalin', 0, true),
(330, 'tanacs', 'dr. Langmáhr Nóra', 0, true),
(331, 'tanacs', 'dr. Lukácsi Beáta Zsuzsanna', 0, true),
(332, 'tanacs', 'dr. Molnár Andrea', 0, true),
(333, 'tanacs', 'dr. Németh Renáta Mária', 0, true),
(334, 'tanacs', 'dr. Oláh Anita', 0, true),
(335, 'tanacs', 'dr. Polgárné dr. Vida Judit', 0, true),
(336, 'tanacs', 'dr. Rabb Zsuzsanna', 0, true),
(337, 'tanacs', 'dr. Rada Krisztina', 0, true),
(338, 'tanacs', 'dr. Radnóti Farkas Fatime', 0, true),
(339, 'tanacs', 'dr. Ribárszki Erzsébet Éva', 0, true),
(340, 'tanacs', 'dr. Ruszinkó Judit', 0, true),
(341, 'tanacs', 'dr. Stráhl Zita', 0, true),
(342, 'tanacs', 'dr. Szabó Györgyi', 0, true),
(343, 'tanacs', 'dr. Szabolcsi-Varga Krisztina', 0, true),
(344, 'tanacs', 'dr. Szigeti Krisztina Mónika', 0, true),
(345, 'tanacs', 'dr. Telkes Adrienne', 0, true),
(346, 'tanacs', 'dr. Tóth Krisztina Nóra', 0, true),
(347, 'tanacs', 'dr. Tömböly Gabriella Tünde', 0, true),
(348, 'tanacs', 'dr. Urhelyi Rita', 0, true),
(349, 'tanacs', 'dr. Varga Márta', 0, true),
(350, 'tanacs', 'dr. Varga Tünde Piroska', 0, true),
(351, 'tanacs', 'Oláhné dr. Tóth Orsolya', 0, true),
(352, 'tanacs', 'Szegváriné dr. Barócsi Eszter', 0, true),
(353, 'tanacs', 'Vámosiné dr. Marunák Ágnes', 0, true),
(354, 'tanacs', 'Vargáné dr. Erdődi Ágnes', 0, true),
(355, 'tanacs', 'Vojnitsné dr. Kisfaludy Atala', 0, true),
(356, 'tanacs', 'dr. Barnóczki-Elsasser Endre', 0, true),
(357, 'tanacs', 'dr. Bóka Mária', 0, true),
(358, 'tanacs', 'dr. Csontos Dániel', 0, true),
(359, 'tanacs', 'dr. Geiger Cecília', 0, true),
(360, 'tanacs', 'dr. Hajdu Koppány', 0, true),
(361, 'tanacs', 'dr. Hortobágyi-Balázs Anett', 0, true),
(362, 'tanacs', 'dr. Horváth Elvira', 0, true),
(363, 'tanacs', 'dr. Huber Zsuzsanna', 0, true),
(364, 'tanacs', 'dr. Imre Péter', 0, true),
(365, 'tanacs', 'dr. Kiss Krisztina', 0, true),
(366, 'tanacs', 'dr. Kreisz Anita', 0, true),
(367, 'tanacs', 'dr. Miczán Péter', 0, true),
(368, 'tanacs', 'dr. Niklai Zoltán', 0, true),
(369, 'tanacs', 'dr. Piti Sándor', 0, true),
(370, 'tanacs', 'dr. Pleszkáts Anikó', 0, true),
(371, 'tanacs', 'dr. Smid Erika', 0, true),
(372, 'tanacs', 'dr. Szita Natasa', 0, true),
(373, 'tanacs', 'dr. Takácsné dr. Éles Anita', 0, true),
(374, 'tanacs', 'dr. Takács-Tóth Tímea', 0, true),
(375, 'tanacs', 'dr. Tantalics Gabriella', 0, true),
(376, 'tanacs', 'dr. Tóth Tímea', 0, true),
(377, 'tanacs', 'dr. Varga Dóra', 0, true),
(378, 'tanacs', 'dr. Varga Erzsébet', 0, true),
(379, 'tanacs', 'dr. Váry Viktória', 0, true),
(380, 'tanacs', 'dr. Veszprémi Ágnes', 0, true),
(381, 'tanacs', 'Illyésné dr. Lantos Emőke', 0, true),
(382, 'tanacs', 'Koósné dr. Berecz Krisztina', 0, true),
(383, 'tanacs', 'Lugosiné dr. László Mónika', 0, true),
(384, 'tanacs', 'dr. Berzétei Dóra', 0, true),
(385, 'tanacs', 'dr. Császma Júlia', 0, true),
(386, 'tanacs', 'dr. Hajtman Veronika', 0, true),
(387, 'tanacs', 'dr. Horváth Orsolya', 0, true),
(388, 'tanacs', 'dr. Kovács Adrienn', 0, true),
(389, 'tanacs', 'dr. Miskolczi Alexandra', 0, true),
(390, 'tanacs', 'dr. Stifter-Dobos Szilvia Krisztina', 0, true),
(391, 'tanacs', 'dr. Szakács Tünde', 0, true),
(392, 'tanacs', 'dr. Szakácsi Márton', 0, true),
(393, 'tanacs', 'dr. Tauber Annamária', 0, true),
(394, 'tanacs', 'dr. Urbán-Nagy Szilvia', 0, true),
(395, 'tanacs', 'dr. Varga Andrea', 0, true),
(396, 'tanacs', 'dr. Vass László', 0, true),
(397, 'tanacs', 'dr. Zana Gabriella', 0, true),
(398, 'tanacs', 'Kovácsné dr. Droblyen Éva', 0, true),
(399, 'tanacs', 'Simonné dr. Peti Viktória', 0, true),
(400, 'tanacs', 'Skeleczné dr. Horváth Judit', 0, true),
(401, 'tanacs', 'dr. Budaházi Ágnes', 0, true),
(402, 'tanacs', 'dr. Felföldi Anikó', 0, true),
(403, 'tanacs', 'dr. Gesztesi Kinga', 0, true),
(404, 'tanacs', 'dr. Gulyás Mária', 0, true),
(405, 'tanacs', 'dr. Kocsis Ilona', 0, true),
(406, 'tanacs', 'dr. Kocsis Ilona', 0, true),
(407, 'tanacs', 'dr. Luczay-Mazula Sándor', 0, true),
(408, 'tanacs', 'dr. Ördög-Korondi Nóra', 0, true),
(409, 'tanacs', 'dr. Provaznik Balázs', 0, true),
(410, 'tanacs', 'dr. Szűcs Réka', 0, true),
(411, 'tanacs', 'dr. Szűcs-Bodnár Réka', 0, true),
(412, 'tanacs', 'dr. Vágó-Paczolay Liliána', 0, true),
(413, 'tanacs', 'dr. Velez-Borossy Gabriella', 0, true),
(414, 'tanacs', 'dr. Zsengellér Ildikó', 0, true),
(415, 'tanacs', 'Ugrin Dánielné dr. Simon Andrea', 0, true),
(416, 'tanacs', 'dr. Horváth István', 0, true),
(417, 'tanacs', 'dr. Jurkinya Richárd', 0, true),
(418, 'tanacs', 'dr. Kozák Beatrix', 0, true),
(419, 'tanacs', 'dr. Kulcsár Mónika', 0, true),
(420, 'tanacs', 'dr. Lénárd-Komjáthy Kitti Kata', 0, true),
(421, 'tanacs', 'dr. Nyújtó Ildikó', 0, true),
(422, 'tanacs', 'dr. Szabó Ágnes', 0, true),
(423, 'tanacs', 'dr. Szotáczky Gergely', 0, true),
(424, 'tanacs', 'dr. Turóczi Emese', 0, true),
(425, 'tanacs', 'dr. Varsányi Nikolett', 0, true),
(426, 'tanacs', 'Kollerné dr. Kovács Éva', 0, true),
(427, 'tanacs', 'Rózsáné dr. Váradi Edina', 0, true),
(428, 'tanacs', 'dr. Acsádi Tímea', 0, true),
(429, 'tanacs', 'dr. Csák Éva', 0, true),
(430, 'tanacs', 'dr. Csák Éva Elnök', 0, true),
(431, 'tanacs', 'dr. Fényes Andrea', 0, true),
(432, 'tanacs', 'dr. Hajdu Emese', 0, true),
(433, 'tanacs', 'dr. Hársvölgyi Zsuzsanna', 0, true),
(434, 'tanacs', 'dr. Igaz Barbara', 0, true),
(435, 'tanacs', 'dr. Kolossváryné dr. Molnár Mónika', 0, true),
(436, 'tanacs', 'dr. Korsós Judit', 0, true),
(437, 'tanacs', 'dr. Molnár Edina Edit', 0, true),
(438, 'tanacs', 'dr. Nyikos Beatrix', 0, true),
(439, 'tanacs', 'dr. Répássy Andrea Katalin', 0, true),
(440, 'tanacs', 'dr. Sándor András', 0, true),
(441, 'tanacs', 'dr. Sipka Dóra', 0, true),
(442, 'tanacs', 'dr. Solymosi Judit', 0, true),
(443, 'tanacs', 'dr. Szabó Andrea', 0, true),
(444, 'tanacs', 'dr. Szöllősi Lajos', 0, true),
(445, 'tanacs', 'dr. Virányi Karolina', 0, true),
(446, 'tanacs', 'Barcsákné dr. Bolykó Ildikó', 0, true),
(447, 'tanacs', 'dr. Bajusz Kata', 0, true),
(448, 'tanacs', 'dr. Balogh Erika', 0, true),
(449, 'tanacs', 'dr. Borbélyné dr. Nagy Judit', 0, true),
(450, 'tanacs', 'dr. Dékány Virág Bernadett', 0, true),
(451, 'tanacs', 'dr. Dózsa Gábor', 0, true),
(452, 'tanacs', 'dr. Faix Nikoletta', 0, true),
(453, 'tanacs', 'dr. Forintos Eszter Szimonetta', 0, true),
(454, 'tanacs', 'dr. Heinemann Csilla', 0, true),
(455, 'tanacs', 'dr. Kávássy Béni Péter', 0, true),
(456, 'tanacs', 'dr. Kocsis Tamás', 0, true),
(457, 'tanacs', 'dr. Korpás-Földi Zsuzsanna', 0, true),
(458, 'tanacs', 'dr. Lohr Veronika', 0, true),
(459, 'tanacs', 'dr. Loránt Judit', 0, true),
(460, 'tanacs', 'dr. Molnos Dániel', 0, true),
(461, 'tanacs', 'dr. Somogyi Petra Zoé', 0, true),
(462, 'tanacs', 'dr. Szántay Eszter Anna', 0, true),
(463, 'tanacs', 'dr. Tóth Zsuzsanna', 0, true),
(464, 'tanacs', 'dr. Tulkán Katalin Ágnes', 0, true),
(465, 'tanacs', 'dr. Albert Zsuzsanna', 0, true),
(466, 'tanacs', 'dr. Baranyai Krisztina', 0, true),
(467, 'tanacs', 'dr. Betyár Beáta', 0, true),
(468, 'tanacs', 'dr. Bozsár Jusztina', 0, true),
(469, 'tanacs', 'dr. Csécsei Etele Ádám', 0, true),
(470, 'tanacs', 'dr. Csongorádi Anita', 0, true),
(471, 'tanacs', 'dr. Előházi Csilla', 0, true),
(472, 'tanacs', 'dr. Harton András Márton', 0, true),
(473, 'tanacs', 'dr. Hatlaczki-Kálmán Andrea', 0, true),
(474, 'tanacs', 'dr. Imre Noémi Judit', 0, true),
(475, 'tanacs', 'dr. Magyar Viktória', 0, true),
(476, 'tanacs', 'dr. Malik Gábor', 0, true),
(477, 'tanacs', 'dr. Nagy Emese', 0, true),
(478, 'tanacs', 'dr. Sándor István', 0, true),
(479, 'tanacs', 'dr. Simon Levente', 0, true),
(480, 'tanacs', 'dr. Szabó Imre Gergely', 0, true),
(481, 'tanacs', 'dr. Szedmák András', 0, true),
(482, 'tanacs', 'dr. Szigethy-Nagy Zsófia', 0, true),
(483, 'tanacs', 'dr. Veszeli Marcell', 0, true),
(484, 'tanacs', 'Gazdusné dr. Fekete Georgina', 0, true),
(485, 'tanacs', 'Gnájné dr. Porkoláb Erika', 0, true),
(486, 'tanacs', 'Juhászné dr. Kádár Beáta', 0, true),
(487, 'tanacs', 'Szabóné dr. Horvai Melinda', 0, true),
(488, 'tanacs', 'Topolánszkyné dr. Brieber Nóra', 0, true),
(489, 'tanacs', 'Balláné dr. Illés Ivett', 0, true),
(490, 'tanacs', 'dr. Ábrahám Judit', 0, true),
(491, 'tanacs', 'dr. Balassa Virág', 0, true),
(492, 'tanacs', 'dr. Balázs-Simon Magdolna', 0, true),
(493, 'tanacs', 'dr. Bárdy Szilvia', 0, true),
(494, 'tanacs', 'dr. Berecz-Fülöp Emese', 0, true),
(495, 'tanacs', 'dr. Bíró Viktória', 0, true),
(496, 'tanacs', 'dr. Csabay-Toásó Erika', 0, true),
(497, 'tanacs', 'dr. Komlós Ádám', 0, true),
(498, 'tanacs', 'dr. Kováts Tamás Attila', 0, true),
(499, 'tanacs', 'dr. Lakatosné dr. Fitos Dóra', 0, true),
(500, 'tanacs', 'dr. Marton Erika', 0, true),
(501, 'tanacs', 'dr. Nyulak Éva', 0, true),
(502, 'tanacs', 'dr. Papp László', 0, true),
(503, 'tanacs', 'dr. Simon Gabriella', 0, true),
(504, 'tanacs', 'dr. Vetési Melinda', 0, true),
(505, 'tanacs', 'dr. Zsirai Lilla', 0, true),
(506, 'tanacs', 'dr. Gyarmati Gabriella', 0, true),
(507, 'tanacs', 'dr. Hermann Zsófia', 0, true),
(508, 'tanacs', 'dr. Horváth Balázs', 0, true),
(509, 'tanacs', 'dr. Oszterhuber Réka', 0, true),
(510, 'tanacs', 'dr. Pap Anikó', 0, true),
(511, 'tanacs', 'Kepesné dr. Bekő Borbála', 0, true),
(512, 'tanacs', 'Patakiné dr. Nemoda Beáta', 0, true),
(513, 'tanacs', 'dr. Kertész Szilvia', 0, true),
(514, 'tanacs', 'dr. Nagy Anett', 0, true),
(515, 'tanacs', 'dr. Rácz Adrienn', 0, true),
(516, 'tanacs', 'dr. Szelei Erika', 0, true),
(517, 'tanacs', 'dr. Viski Zoltán', 0, true),
(518, 'tanacs', 'Labanczné dr. Ficsor Adél', 0, true),
(519, 'tanacs', 'dr. Balogh László', 0, true),
(520, 'tanacs', 'dr. Demeter Éva', 0, true),
(521, 'tanacs', 'dr. Kasztory László', 0, true),
(522, 'tanacs', 'dr. Király Edit', 0, true),
(523, 'tanacs', 'dr. Molnár Dalma', 0, true),
(524, 'tanacs', 'dr. Nagy Renáta Hajnalka', 0, true),
(525, 'tanacs', 'dr. Parti Zsuzsanna', 0, true),
(526, 'tanacs', 'dr. Plausin Éva', 0, true),
(527, 'tanacs', 'Keményné dr. Forgács Dóra', 0, true),
(528, 'tanacs', 'dr. Bajnokné Kováts Györgyi', 0, true),
(529, 'tanacs', 'dr. Bán Zsuzsanna', 0, true),
(530, 'tanacs', 'dr. Baráth Géza', 0, true),
(531, 'tanacs', 'dr. Eördögh-Leszák Andrea', 0, true),
(532, 'tanacs', 'dr. File Zsuzsanna', 0, true),
(533, 'tanacs', 'dr. Kiss Nóra', 0, true),
(534, 'tanacs', 'dr. Krajnyák Erika', 0, true),
(535, 'tanacs', 'dr. Kuhár Anna Erzsébet', 0, true),
(536, 'tanacs', 'dr. Lőkös Anna', 0, true),
(537, 'tanacs', 'dr. Mátyás Klára', 0, true),
(538, 'tanacs', 'dr. Móri Krisztina', 0, true),
(539, 'tanacs', 'dr. Nagyváradi Izolda Anikó', 0, true),
(540, 'tanacs', 'dr. Seres Péter', 0, true),
(541, 'tanacs', 'dr. Szentkereszty András', 0, true),
(542, 'tanacs', 'dr. Vida-Lukácsi Katalin', 0, true),
(543, 'tanacs', 'dr. Vitai Fruzsina', 0, true),
(544, 'tanacs', 'dr. Barnóczki Péter', 0, true),
(545, 'tanacs', 'dr. Bata Ágnes', 0, true),
(546, 'tanacs', 'dr. Bicskei Tamás', 0, true),
(547, 'tanacs', 'dr. Drahota Anett', 0, true),
(548, 'tanacs', 'dr. Holló Ágnes', 0, true),
(549, 'tanacs', 'dr. Juni Zsuzsanna', 0, true),
(550, 'tanacs', 'dr. Kacsóh Lilla', 0, true),
(551, 'tanacs', 'dr. Nagy Barbara', 0, true),
(552, 'tanacs', 'dr. Papp Renáta', 0, true),
(553, 'tanacs', 'dr. Ruckel-Pandazis Orsolya', 0, true),
(554, 'tanacs', 'dr. Sárközi Eszter', 0, true),
(555, 'tanacs', 'dr. Serfőző Ágnes', 0, true),
(556, 'tanacs', 'dr. Steffel Boglárka', 0, true),
(557, 'tanacs', 'dr. Sztanó Anita', 0, true),
(558, 'tanacs', 'dr. Tolnai Eszter', 0, true),
(559, 'tanacs', 'dr. Víg Zita Veronika', 0, true),
(560, 'tanacs', 'Szűrösné dr. Takács Andrea', 0, true),
(561, 'tanacs', 'Daláné dr. Sándor Zita', 0, true),
(562, 'tanacs', 'Domjánné dr. Hajzsel Krisztina', 0, true),
(563, 'tanacs', 'dr. Antal Ágnes', 0, true),
(564, 'tanacs', 'dr. Ilonczai Ilona', 0, true),
(565, 'tanacs', 'dr. Kerekes József', 0, true),
(566, 'tanacs', 'dr. Klimászné dr. Mikes Eszter', 0, true),
(567, 'tanacs', 'dr. Molnár Zsolt', 0, true),
(568, 'tanacs', 'dr. Nógrádi Krisztián', 0, true),
(569, 'tanacs', 'dr. Palkovics-Révész Dalma', 0, true),
(570, 'tanacs', 'dr. Petri Dávid', 0, true),
(571, 'tanacs', 'dr. Tasi Katalin', 0, true),
(572, 'tanacs', 'dr. Ujvári Andrea', 0, true),
(573, 'tanacs', 'dr. Vavroh Géza', 0, true),
(574, 'tanacs', 'Kocsisné dr. Niedermüller Angelika', 0, true),
(575, 'tanacs', 'Redlné dr. Mészáros Ildikó', 0, true);
